name: Build, Test & Deploy
on:
  push:
jobs:
  build-test-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ðŸ›Žï¸
        uses: actions/checkout@v2.4.0

      - name: Setup Node.js ðŸ¤–
        uses: actions/setup-node@v2
        with:
          node-version: '15'

      - name: Install and Build ðŸ”§
        run: |
          npm ci
          npm run build
      
      - name: Cypress Test ðŸ‡¨ðŸ‡¾
        run: |
          npm run cypress:ci

      - name: Lint ðŸ§¶
        run: |
          npm run lint

      - name: Version File ðŸ—‚
        run: echo ${{ github.sha }} > public/version.txt

      - name: Deploy ðŸš€
        if: github.ref == 'refs/heads/main'
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          branch: gh-pages
          folder: public
